FROM debian:buster
#FROM debian:stretch
RUN apt-get update && \
    apt-get install -y \
      git python3 python3-pip python3-dnspython python3-matplotlib python3-pytest python3-bs4 && \
    apt-get clean && \
    pip3 install \
      slackclient==1.3.2

# change openssl security level in buster
ADD ./openssl.cnf /tmp
RUN /bin/bash -c 'grep -F -s 10. /etc/debian_version > /dev/null && \
                  cp /tmp/openssl.cnf /etc/ssl'

WORKDIR /root/project

# pusedo temperature sensor
ADD ./w1_slave.py /root/project

CMD ["/bin/bash"]
